Title.create({Emp_No: 1111, title:"Boss-man"})
Title.create({Emp_No: 2222, title:"Wizard"})
Title.create({Emp_No: 3333, title:"Peon"})
Title.create({Emp_No: 4444, title:"Newbie"})

Employee.create({Emp_No: 1111, First_Name:"Joe", Last_Name:"Shmoe", Gender:1})
Employee.create({Emp_No: 2222, First_Name:"Terrence"})
Employee.create({Emp_No: 3333, First_Name:"David"})
Employee.create({Emp_No: 4444, First_Name:"Joshua"})
Employee.create({Emp_No: 5555, First_Name:"Musa"})